### ISSUE TITLE
Login redirections

### ISSUE THREAD

**Issue by thomas-robert-heig** [websauce-projart/roesti-quiz#2]
**To fix**,
* [x] User is not redirected after logged-in
* [x] Login page is accessible after logged-in
* [x] "Retrieve e-mail" button appears after log-in
* [x] Redirect admin on backoffice
* [x] A non verified user get redirected too many times when trying to login

**Comment by fly04** [comment]
Login page is no more accessible after being logged-in

**Comment by fly04** [comment]
A verified user is now redirected after being logged-in

**Comment by fly04** [comment]
"Retrieve e-mail" button now appears after log-in.
The redirect issue is fixed aswell.

**Comment by fly04** [comment]
Admins are now redirected in the backoffice when logged
