### ISSUE TITLE
Missing or incorrect questions

### ISSUE THREAD

**Issue by fly04** [websauce-projart/roesti-quiz#20]
Some questions are missing, some have orthographic mistakes, some are incorrect, some have incorrect category 
![image](https://user-images.githubusercontent.com/46554723/121777438-53693680-cb92-11eb-9c42-7a7ffcd6f3da.png)
![image](https://user-images.githubusercontent.com/46554723/121777447-611ebc00-cb92-11eb-88f7-e68b7400e8c1.png)
![image](https://user-images.githubusercontent.com/46554723/121777448-6845ca00-cb92-11eb-9ffb-22dd1eeb7021.png)
![image](https://user-images.githubusercontent.com/46554723/121777472-90cdc400-cb92-11eb-9019-c8795933048f.png)
![image](https://user-images.githubusercontent.com/46554723/121777506-c2df2600-cb92-11eb-9114-d2115e935a4f.png)

**Comment by Zekarim** [comment]
Waiting for the feedback of UX on the changes.
