### ISSUE TITLE
Quit in-game handling

### ISSUE THREAD

**Issue by thomas-robert-heig** [websauce-projart/roesti-quiz#7]
The user can't go back on a game he started and quitted (ex. close the browser and come back).

The behviour should ideally be: answers are posted in current state after user quit the game (unanswered questions are null, so considered wrong)

**Comment by fly04** [comment]
To fix in ShowQuizView method in QuizController

**Comment by fly04** [comment]
A fix has been implemented, if a user quit while in game, when he goes to the results and press play, he get directly redirected to the endgame route with all answers as false and a score of 0. Seems to work fine but more testing is needed.
