### ISSUE TITLE
Score/points algorithme

### ISSUE THREAD

**Issue by thomas-robert-heig** [websauce-projart/roesti-quiz#8]
Implement how the score is handle.

Maybe something like:
100_base_points - time - (10 * nbr_of_wrong_answers)

**Comment by fly04** [comment]
Added a first algorithm draft, to refine as we test

**Comment by Smettraux** [comment]
Score now handled as 
==============
`modifier` * `correct answers` / `seconds elapsed`

base modifier : 1500

→ _modifier_ upped to 2000 to make it easier for the testers. May be way too easy now.

**Comment by Smettraux** [comment]
modifier is now 1500 again.

Issue closed.
